### ISSUE TITLE
Shiny server link is down

### ISSUE THREAD

**Issue by aravind-j** [gertstulp/ggplotgui#2]
The link [ https://site.shinyserver.dck.gmw.rug.nl/ggplotgui/]( https://site.shinyserver.dck.gmw.rug.nl/ggplotgui/) shows the following error:

`ERROR: An error has occurred. Check your logs or contact the app author for clarification.`

**Comment by sfd99** [comment]
same here...

**Comment by gertstulp** [comment]
Thanks for the creating the issue; I hope it's fixed now!

**Comment by GegznaV** [comment]
The link works fine at the moment. I recommend @gertstulp  to close #2
